excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Kaskat123.github.io
title: Salvadorian News
tagline: Updating ou on the latest mission news
description: THis is a blog for Rivercliff's mission trip to El Salvador! I will be posting everyday updating you guys on what we are doing here and how much fun and an impact we are creating. Stay Tuned! T-minus 2 days till take off!
paginate: 10